version: '3.7'
services:
  oracle:
    image: gvenzl/oracle-free:latest
    environment:
      ORACLE_RANDOM_PASSWORD: true
      APP_USER: my_user
      APP_USER_PASSWORD: password_i_should_change
    ports:
      - "1521:1521"
    healthcheck:
      test: [ "CMD", "healthcheck.sh" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
      start_interval: 5s
    restart: on-failure
    networks:
      - boilerplate
networks:
  boilerplate: