version: '3.7'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-kotlin-oracle
    ports:
      - "8082:8082"
    restart: no
    environment:
      SERVER_PORT: 8082
    networks:
      - boilerplate
    depends_on:
      - oracle
  oracle:
    #https://hub.docker.com/r/gvenzl/oracle-free
    image: gvenzl/oracle-free:latest
    environment:
      ORACLE_RANDOM_PASSWORD: true
      APP_USER: my_user
      APP_USER_PASSWORD: password_i_should_change
    ports:
      - "1521:1521"
    healthcheck:
      test: [ "CMD", "healthcheck.sh" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
      start_interval: 5s
    restart: on-failure
    networks:
      - boilerplate
volumes:
  oracle_data:
networks:
  boilerplate: